In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


   0.0000    0.0000    0.0000
   0.0000       nan    0.0000
  44.8020    0.0000    0.0000
   0.0000    0.0000   12.3243
   0.0000  776.8779    0.0365
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [4]:
x = torch.rand(5, 3)
print(x)


 0.2590  0.1257  0.8627
 0.0822  0.7717  0.5890
 0.7819  0.8441  0.0367
 0.5471  0.3748  0.7457
 0.5654  0.3423  0.8356
[torch.FloatTensor of size 5x3]



Get its size



In [5]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(x + y)


 0.3293  0.9506  1.5417
 0.4204  1.3451  1.1966
 0.8818  1.7882  0.8798
 1.3457  0.6772  0.7997
 1.1958  0.9598  0.9165
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 0.3293  0.9506  1.5417
 0.4204  1.3451  1.1966
 0.8818  1.7882  0.8798
 1.3457  0.6772  0.7997
 1.1958  0.9598  0.9165
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.3293  0.9506  1.5417
 0.4204  1.3451  1.1966
 0.8818  1.7882  0.8798
 1.3457  0.6772  0.7997
 1.1958  0.9598  0.9165
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 0.3293  0.9506  1.5417
 0.4204  1.3451  1.1966
 0.8818  1.7882  0.8798
 1.3457  0.6772  0.7997
 1.1958  0.9598  0.9165
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [10]:
print(x[:, 1])


 0.1257
 0.7717
 0.8441
 0.3748
 0.3423
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [11]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [12]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [13]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [16]:
# let us run this cell only if CUDA is available
print(torch.cuda.is_available())
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)

True

 0.5884  1.0763  2.4044
 0.5026  2.1168  1.7856
 1.6637  2.6322  0.9164
 1.8928  1.0519  1.5454
 1.7612  1.3020  1.7522
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

